services:

  devsecops-app:
    image: donibawono/devsecops-flask:v0.0.7
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devsecops-app
    hostname: devsecops-prod
    ports:
      - "5001:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    networks:
      - devsecops-network

networks:
  devsecops-network:
    driver: bridge