name: Protect Main Branch

on:
  workflow_call:

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"

          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Only PRs from 'dev' branch are allowed to merge into 'main'"
            exit 1
          fi